
clear
Folder = '/data/jux/BBL/projects/pncSingleFuncParcel/Dale/PET';
% left hemisphere
PET_fsaverage6_lh = load([Folder '/CMRGlu_L_fsaverage6.txt']);
V_lh = gifti;
V_lh.cdata = PET_fsaverage6_lh;
V_lh_File = [Folder '/lh.PET_CMRGlu_fsaverage6.func.gii'];
save(V_lh, V_lh_File);

PET_fsaverage6_lh = [Folder '/lh.PET_CMRGlu_fsaverage6.func.gii'];
cmd = ['wb_command -metric-resample ' PET_fsaverage6_lh ' ' ...
       Folder '/fsaverage6/fsaverage6_std_sphere.L.41k_fsavg_L.surf.gii ' ...
       Folder '/HCP_32k/fs_LR-deformed_to-fsaverage.L.sphere.32k_fs_LR.surf.gii ' ...
       'ADAP_BARY_AREA ' ...
       Folder '/PET_CMRGlu.lh.HCP_32k.func.gii ' ...
       '-area-metrics ' ...
       Folder '/fsaverage6/fsaverage6.L.midthickness_va_avg.41k_fsavg_L.shape.gii ' ...
       Folder '/HCP_32k/fs_LR.L.midthickness_va_avg.32k_fs_LR.shape.gii'];
system(cmd);

% right hemisphere
PET_fsaverage6_rh = load([Folder '/CMRGlu_R_fsaverage6.txt']);
V_rh = gifti;
V_rh.cdata = PET_fsaverage6_rh;
V_rh_File = [Folder '/rh.PET_CMRGlu_fsaverage6.func.gii'];
save(V_rh, V_rh_File);

PET_fsaverage6_rh = [Folder '/rh.PET_CMRGlu_fsaverage6.func.gii'];
cmd = ['wb_command -metric-resample ' PET_fsaverage6_rh ' ' ...
       Folder '/fsaverage6/fsaverage6_std_sphere.R.41k_fsavg_R.surf.gii ' ...
       Folder '/HCP_32k/fs_LR-deformed_to-fsaverage.R.sphere.32k_fs_LR.surf.gii ' ...
       'ADAP_BARY_AREA ' ...
       Folder '/PET_CMRGlu.rh.HCP_32k.func.gii ' ...
       '-area-metrics ' ...
       Folder '/fsaverage6/fsaverage6.R.midthickness_va_avg.41k_fsavg_R.shape.gii ' ...
       Folder '/HCP_32k/fs_LR.R.midthickness_va_avg.32k_fs_LR.shape.gii'];
system(cmd);


